Repository mycelium-com/bitcoincashj, pull requests merged in 2018-03, with the labels that each got.

#7 Too many peers connection fix
  core/src/main/java/org/bitcoinj/core/PeerGroup.java
Labels: bug

#8 added gradle support
  .gitignore
  build.gradle
  core/build.gradle
  examples/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  tools/build.gradle
  wallettemplate/build.gradle
Labels: maintenance

#9 added gradle support
  .gitignore
  build.gradle
  core/build.gradle
  examples/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  patch.patch
  settings.gradle
  tools/build.gradle
  wallettemplate/build.gradle
Labels: enhancement, maintenance
